### PR TITLE
add eytzinger to benchmarks

### LINKED ISSUE #369: boost::histogram::axis::variant, allow users to choose between sorted_array+std::lower_bound and eytzinger_layout+eytzinger_binary_search
According to the test,

- When input follows normal distribution, sorted_array+std::lower_bound is faster;
- When input follows uniform distribution, eytzinger_layout+eytzinger_binary_search is faster;
[Eytzinger Binary Search - Algorithmica](https://algorithmica.org/en/eytzinger)
[Static B-Trees: up to 15x faster than std::lower_bound : cpp](https://www.reddit.com/r/cpp/comments/sv012b/static_btrees_up_to_15x_faster_than_stdlower_bound/)

(`boost::histogram::axis::variant` is currently using `std::upper_bound`.)

[comparison (x86-64 gcc (trunk), -std=c++23 -O3 -Wall -pedantic -pthread)](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAA7ACspAAOqAqETgwe3r56KWmOAkEh4SxRMQm2mPYFDEIETMQEWT5%2BXJXVGXUNBEVhkdF6CvWNzTltQ929JWUSAJS2qF7EyOwc5gDMScRMwCxMANQA4m5u%2B6hJjix4AF6YEOZmAPLrD7MmGgCCG8HI3lj7JnWbgihAUAHohuhTJZrAA6BCA7DvL6fNAMIaYVRbfZpW4AfQI%2BwYAPWABF9hAuIC3NSzBo3usrKiBBiscQcTdMAT9hFaKhkABrPG4zAk8kANkk%2BzBHNuqCoEGCBAZFmlMsBEqlMqlGv2omQCC5tGCXJF0tlmHlisEb0%2BYjwwGYCggktm%2ByV%2ByYJniFgY3tJpB53t91ip8VJgKZKI%2BaNZ2JF3IAjl5ogBPPFoLyCDWU6m0%2BmR5Ee4bATAEBTB5NpjOLbPhwufD3ETAKLy0ct4zCpgjXYKl4iVlPEdOZusRxlFwT7Zut9sKPF8gDu0TxEVr6EH1dHBH9DejHq7Pb70WthLwYv2GkDCcJAovXDdJliUf2r/dVApd7zZKJj%2BfyLfQD3QvQ9eyME88EDMx9gAKn2AUVQAoDXwiYMBX9C8vR9PBrFw%2BsJ0%2BZDX3PXVQOPYhFSg2D4IBSx9gfPdAKfCNCLfZsCCWYkcIIr5YhY/cpyUBoDVPfZVD/F83xvGjdSpHjAMXBA6FFCAvyBXUGAkpDkLxVcvDoRwGDxLZMCoMsRIiWjVTvODeX5IURUQ1jkLU8loLgr86IgVCfXQ8MSVOcTGLfZjtJk9YkQi3VdIifT22CPEqCoZ0AD8EOC192M4%2BC91Cz5J0JPZgggW1eMk19IRAEBtgYdBUBYPEsAANzwFZpw3RlXzBMEAHU6FoHlRS8JR0H2Igzgiepgk9HFMEwUb%2BHZAhDWnQw6pYIl%2BnZRhgBNMLKpAFgCC4ABOE71lifZSwYCBiHQEqVTVLpaoaUa2GIJQGBCAlFzwDFiE7IwTVm%2Bb5v2X7lvakr9oIdAqqzPBFoapVGr%2BghiDwWKam/bB9nwIYMYiCADoYHxolahc8CuctqSVREqquG75hxWGqtJ96KeNamKyBOmIoZphVAejL9kWilpJIn8NEjYCwDADSZdwyw8FKpj/2coCsIsHD8NJA7iHXCB8fRzHoEYWYnI%2BNX%2BMAg6FBIAhidZkAol2m6mHmA7XAgD3LbCsjwIov2NbF4nOW5SXyWlzrzzl3Uq2HGssx3Tqle11WQvVq2iJLMsK2w3cyX1w3jcJs3NMt63kTCp9ys1rxxomRoLwOg0DYYVAqoxJh0BHPlBTZ1BF2h%2BSiNDiWL2j1VY/ln8E5HWsU9VNOVbCtW66I6cWzbDsA/7YMdfHPXMGEhAIFzmmC/DSuiLy7PkKYBvUH2VwW%2BdtuBE7kBu97jN%2B4FQew8b7IVbggduX90BLCYNjIEdUvC8kwIiF%2BBgkgjWFJgNE6AFAgVqgAWibkvNeUl36LEJN%2BU4DwqhMFQWDS47BaLQXIcg6haClCYIULCbcJUArUgYfnNwfozBmBFnfdeRDXyP0bsMMhP5QHgK7gQE%2Bv9fj2UASPDeb5x7hzPJPGWM945DgXsnRWMJlYZ2QrXcRQEZw73nEuFca4swbivkfA69iAaONqk7OGLtMBux9p7Z23sPakAvvnbW/pZj4Odq7YqHsRZVw1oBSRz9X66jkZ/BRSi%2B6qJAB3IBCTiE%2BI/h3KqkDtgwLcHAhBSCqE0PQOg9hOD0DRO6IUiqJCG48KBAwupI0xpU3oQ8bppw%2BnzUaQILBnDF7cKYQ8fhgjhGj1fKIzRJBxbaOArqKestZ7knnknbMqdTHpxrlnTeTAFBKEaD7YMNi5wLiHg49cB9dy6w1D5Cw9zd7djAvvFxkSZYrI1nfO%2BHB5i0E4PEXgfgOBaFIJ3DgNITk4kWMsUUGweChM0OC%2BYAD4hXkhRwSQvAWAgElLCAAHBoSl6xxRmDpedC6J1KWkFhfCxFvAFAgCvAQHF8w4CwCQGgFgSRlJkAoBAEVYr6AxGAAoZgqCECoAIKQZqrVMAADU8CYEXI8JIjBOBYpoO2aI3LvI4tICCZgw4jW8BFWwQQjwGC0FTJarAewjDiDhbwfAzYHB4Cai2S1mIMEN1WFipUVRLXGgiNsYcHgsCWpNmS7g4K%2BAGHldq3V%2BrDVppkIIEQYh2BSALfIJQahLW6DaAYIwKA076ExtyyA8xzg1G5RwaJHVSTQisJYBl%2BxcHPEHT1MQA1cEGvQIYRwyBB0XDAUorlVQME1BcLVUYrRSCBBNNMAYbQ8jpAEBu3IqRD0MCmFtQYy6A0CC6CMTwLQr0dFvdIi9pQ922Gkce8Yr6d2XofAsJYKw5j6ChTCy1iKxKUvFLgyUV1kCzvPsQLMCEKS4EIOszFsxeB8p9QKpAobkBPwlZQBo8rlCGCqEIZVi5YVYulXQaBGQKMhFoNRoe7L7X1RlQMeViqFDKtVQx2VjwG7sdoyG1QGCPjEHlZwXghG6j4FhbwfghbRDiFLWp8tKh1A%2BtINW/QhhjANtjc2kqCKLgZA7V2jUvbrADqHesEdY653zWna1Ody1mw9y5Wi4DP7lMsaozRujOHmwRt4IubYSQ7UQrA2yiDnBsBSaI0QdkqhoOwalMABDFJ0YobdBAZFfabD7HQ%2Bl2i6wHw4f5fMQ0PcBgWaJSS0gZL1jxFhKdLg4oLq9Y0OKelGgzCJf05y2wehcNaAtqQABXANCEs4OscDY35PYrw/MINH0MggEkEAA):
```C++
#pragma GCC optimize("O3")
#include <bits/stdc++.h>

constexpr size_t n = (1<<20);
constexpr size_t block_size = 64 / sizeof(int); // = 64 / 4 = cache_line_size / sizeof(int)
alignas(64) int a[n], b[n+1];

constexpr size_t query_count=(1<<20);
int targets[query_count];
int results_eytzinger[query_count];
int results_lower_bound[query_count];

int eytzinger(int i = 0, size_t k = 1) {
    if (k <= n) {
        i = eytzinger(i, 2 * k);
        b[k] = a[i++];
        i = eytzinger(i, 2 * k + 1);
    }
    return i;
}

int search(int x) {
    size_t k = 1;
    while (k <= n) {
        __builtin_prefetch(b + k * block_size);
        k = 2 * k + (b[k] < x);
    }
    k >>= __builtin_ffs(~k);
    return k;
}

int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(std::numeric_limits<int>::min(), std::numeric_limits<int>::max());
    for (size_t i = 0; i != n; ++i)
    {
        a[i]=std::round(distrib(gen));
    }
    std::sort(std::begin(a),std::end(a));

    eytzinger();

    for (size_t i = 0; i != query_count; ++i)
    {
        targets[i]=std::round(distrib(gen));
    }

    {
        auto start = std::chrono::steady_clock::now();
        for (size_t i = 0; i != query_count; ++i)
        {
            results_eytzinger[i]=search(targets[i]);
        }
        auto end = std::chrono::steady_clock::now();
        std::chrono::duration<double> elapsed_seconds = end-start;
        std::cout << "elapsed time: " << elapsed_seconds.count() << "s\n";
    }
    {
        auto start = std::chrono::steady_clock::now();
        for (size_t i = 0; i != query_count; ++i)
        {
            results_lower_bound[i]=std::lower_bound(std::begin(a),std::end(a),targets[i])-std::begin(a);
        }
        auto end = std::chrono::steady_clock::now();
        std::chrono::duration<double> elapsed_seconds = end-start;
        std::cout << "elapsed time: " << elapsed_seconds.count() << "s\n";
    }
    for (size_t i = 0; i != query_count; ++i)
    {
        assert(a[results_lower_bound[i]]==b[results_eytzinger[i]]);   
    }
}
```
image

### PR DESCRIPTION
**Pull request by HDembinski**
Replace standard search in axis::variable with faster eytzinger search.

Closes #369 

@jhcarl0814 Please fork this branch to work on this feature. I made a start and added the benchmark.

#### To-do
- [x] HD: fix the bugs so the tests run again (this has to happen first)
- [ ] Implement eytzinger_search as an implementation detail (`histogram/detail/eytzinger_search.hpp`)
- [ ] Replace standard search in `axis/variable.hpp` with new search, calling implementation in `detail/eytzinger_search.hpp`
- [ ] Check that implementation works as expected and is faster (existing tests should all pass, perhaps we need further tests)

### CODE REVIEW

**Comment by jhcarl0814** [comment]
@HDembinski I was trying to reproduce the errors caused by clang version changing from 10 to 14 (seems the commit disappered at this noon so do the errors). But following `boost/libs/histogram/CONTRIBUTING.md`, running tests and examples gives no error, running coverage (the `tools/cov.sh` does not exist so I ran `python3 tools/cov.py`) gives an empty `coverage-report` directory.
If I can not reproduce those errors, something must be wrong in my commands:
```
on Windows 11 C:/, shift + right_click >> Open Linux Shell Here
(CONTRIBUTING.md https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview :)
git clone --recursive https://ghp_...@github.com/boostorg/boost.git
cd boost
git checkout develop
./bootstrap.sh
./b2 headers

cd libs/histogram/
git remote add forking_repo https://ghp_...@github.com/jhcarl0814/histogram.git
git fetch forking_repo
git checkout -b eytzinger_search forking_repo/eytzinger_search

../../b2 cxxstd=latest warnings-as-errors=on test -j4
../../b2 cxxstd=latest examples -j4

sudo apt install python3-pip
pip install b2filt
PATH="$PATH:/home/eajniah/.local/bin"
b2filt cxxstd=latest warnings-as-errors=on test -j4
b2filt cxxstd=latest examples -j4

(https://stackoverflow.com/questions/62215963/how-to-install-gcc-and-gdb-for-wslwindows-subsytem-for-linux :)
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install gcc-8 -y
sudo apt-get install g++-8 -y
../../b2 toolset=gcc-8 cxxstd=latest coverage=on test
```

**Comment by HDembinski** [comment]
I fixed the bugs a few hours ago, you can implement your code now.

**Comment by HDembinski** [comment]
@jhcarl0814 I found a cross-platform implementation of prefetch in Boost.Context (it often pays off to mine Boost code for hidden gems). I added that so that we can experiment with it. On my platform, prefetch does not improve performance.

**Comment by jhcarl0814** [comment]
@HDembinski That's cool! At least the missing part is filled. Maybe there are other scenarios or platforms that will benefit from it, but we don't know yet. We'll see.

**Comment by jhcarl0814** [comment]
@HDembinski Sorry to trouble you, this is my first time to do PR.

The change (has passed `b2filt cxxstd=latest warnings-as-errors=on test -j4` and `b2filt cxxstd=latest examples -j4`) has been pushed to https://github.com/jhcarl0814/histogram/tree/eytzinger_search 's `eytzinger_search` branch.

The forking_repo's `eytzinger_search` branch is one commit ahead of https://github.com/boostorg/histogram 's `eytzinger_search` branch.

Should I `git push origin eytzinger_search` or `git fetch origin develop; git merge develop; git push origin eytzinger_search` or ...?

image

The git remote config is like this:
```
eajniah@jhcarl0814_1:/mnt/c/boost/libs/histogram$ git branch -a
  develop
* eytzinger_search
  remotes/forking_repo/develop
  remotes/forking_repo/exact_regular
  remotes/forking_repo/experimental_index_transform
  remotes/forking_repo/eytzinger_search
  remotes/forking_repo/fix_clang5
  remotes/forking_repo/fixes_for_latest_compilers
  remotes/forking_repo/master
  remotes/forking_repo/multi_weight
  remotes/forking_repo/remove_internal_span
  remotes/forking_repo/unsafe_access_accumulators
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
  remotes/origin/exact_regular
  remotes/origin/experimental_index_transform
  remotes/origin/eytzinger_search
  remotes/origin/fix_clang5
  remotes/origin/master
  remotes/origin/multi_weight
  remotes/origin/remove_internal_span
  remotes/origin/unsafe_access_accumulators
eajniah@jhcarl0814_1:/mnt/c/boost/libs/histogram$ git remote -v
forking_repo    https://ghp_...@github.com/jhcarl0814/histogram.git (fetch)
forking_repo    https://ghp_...@github.com/jhcarl0814/histogram.git (push)
origin  https://ghp_...@github.com/boostorg/histogram.git (fetch)
origin  https://ghp_...@github.com/boostorg/histogram.git (push)
```

---

The default layout_and_algorithm is controled by default type template parameter in `boost::histogram::axis::`
include\boost\histogram\fwd.hpp
```C++
struct sorted_array_and_binary_search{};
struct eytzinger_layout_and_eytzinger_binary_search{};
template <class Value = double, class MetaData = use_default, class Options = use_default,
          class Allocator = std::allocator<Value>, class DataStructure = eytzinger_layout_and_eytzinger_binary_search>
class variable;
```

The actual code of each layout_and_algorithm is in `boost::histogram::detail::`
include\boost\histogram\detail\eytzinger_search.hpp
```C++
template <typename T = double>
struct sorted_array_and_binary_search {...};
template <typename T = double>
struct eytzinger_layout_and_eytzinger_binary_search {...};
```

**Comment by jhcarl0814** [comment]
There are some other very small problems found when reading the code:

# 1

`boost::histogram::axis::variable` replaces `boost::use_default` type template parameters (with default types) inside class body. The problem is: we get different types, with exactly same behavior.

- Users might find it's not possible to "determine whether two variable have exactly same behavior" by using `std::is_same_v<decltype(...),decltype(...)>` and have to take on the burden themselves (e.g. add a `xxx_traits` system).
- The complexity also leaks to complicate those functions that receives `boost::histogram::axis::variable` (e.g. assignment operators and comparison operators).
- Template deduction deduces to many `boost::use_default` instead of the more useful actually used types.

It would be better to let user use a type alias and seldom use the class template name, so the conditional operations can terminate at the type alias and does not propagate further.
```C++
namespace boost
{
    namespace histogram
    {
        namespace axis
        {
//            template<class Value = double, class MetaData = use_default, class Options = use_default, class Allocator = std::allocator<Value>, class DataStructure = eytzinger_layout_and_eytzinger_binary_search>
//            using variable_t = boost::histogram::axis::variable<
//              std::conditional_t<std::is_same_v<Value, use_default>, double, Value>,
//              std::conditional_t<std::is_same_v<MetaData, use_default>, std::string, MetaData>,
//              std::conditional_t<std::is_same_v<Options, use_default>, decltype(option::underflow | option::overflow), Options>,
//              std::conditional_t<std::is_same_v<Allocator, use_default>, std::allocator<std::conditional_t<std::is_same_v<Value, use_default>, double, Value>>, Allocator>,
//              std::conditional_t<std::is_same_v<DataStructure, use_default>, eytzinger_layout_and_eytzinger_binary_search, DataStructure>
//              >;
            
            template<class Value = double, class MetaData = use_default, class Options = use_default, class Allocator = std::allocator<Value>, class DataStructure = eytzinger_layout_and_eytzinger_binary_search>
            using variable_t = boost::histogram::axis::variable<
              detail::replace_default<Value,double>,
              detail::replace_default<MetaData,std::string>,
              detail::replace_default<Options,decltype(option::underflow | option::overflow)>,
              detail::replace_default<Allocator,std::allocator<detail::replace_default<Value,double>>>,
              detail::replace_default<DataStructure,eytzinger_layout_and_eytzinger_binary_search>
              >;
        }
    } // namespace histogram
} // namespace boost
static_assert(!std::is_same_v<boost::histogram::axis::variable<double, std::string, boost::use_default>, boost::histogram::axis::variable<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)>>);
static_assert(std::is_same_v<boost::histogram::axis::variable_t<double, std::string, boost::use_default>, boost::histogram::axis::variable_t<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)>>);
```

# 2

`template <class It, class = detail::requires_iterator<It>> variable(It begin, It end, metadata_type meta = {}, options_type options = {}, allocator_type alloc = {})` does not provide strong exception guarantee: if user writes `variable(it_begin, it_end, std::move(str))` and constructor body throws then the value inside `str` is lost (the value was moved into parameter and then data member before the exception). So one can not write `while(std::cin>>str>>...){ try{ variable(..., ..., str); ... }catch(...){} }` and has to take on the burden of saving the `str` elsewhere (so the user do not have to type it again) when other constructor arguments might be illegal and have to be typed again.

# 3

The `if (options_type::test(option::circular))` inside `index_type index(value_type x)` and `value_type value(real_index_type i)` reminds me of when I was dealing with periodic argument reduction in a simulator+monitor program (every ms PC sends sin(A*t+B) and receives actual value to&from a chip through UDP, t can be as large as several days). There should be some high precision functions in boost.core/utility/utilities/tool/tools/toolbox/... and we just need to find them.
https://en.cppreference.com/w/cpp/numeric/lerp
https://stackoverflow.com/questions/64058564/single-precision-argument-reduction-for-trigonometric-functions-in-c
```C++
{
    // using A = axis::variable<double, axis::null_type, op::circular_t>; // using double solves the errors
    using A = axis::variable<float, axis::null_type, op::circular_t>;
    auto a = A({
      1.,
      1e+8,
      2e+8,
    });
    BOOST_TEST_EQ(a.index(1e8), 1);
    BOOST_TEST_EQ(a.index(2e8), 0); // test 'a.index(2e8) == 0' ('-1' == '0') failed
    BOOST_TEST_EQ(a.index(4e8), 0); // test 'a.index(4e8) == 0' ('-1' == '0') failed
}
{
    // using A = axis::variable<double, axis::null_type, op::circular_t>; // using double solves the errors
    using A = axis::variable<float, axis::null_type, op::circular_t>;
    auto a = A({
      -2e+8,
      -1e+8,
      -1.,
    });
    BOOST_TEST_EQ(a.index(-1e8), 1);
    BOOST_TEST_EQ(a.index(-2e8), 0);
    BOOST_TEST_EQ(a.index(-4e8), 1); // test 'a.index(-4e8) == 1' ('0' == '1') failed
}
return boost::report_errors();
```

**Comment by HDembinski** [comment]
Your points 1 to 3 sound interesting, but I do not fully understand you yet.

1) The idea behind boost::use_default is that the default can be changed locally at the implementation site. It is an established pattern in boost. I am not sure what you specifically propose to change. The two blocks of code, the commented and uncommented one, look the same to me. detail::replace_default is syntactic sugar for `std::conditional_t<std::is_same_v<Value, use_default> ... >`.

2) How would you provide the strong exception guarantee? In general, we do not know how MetaData is implemented, when it is user-defined.

3) If there is a way to make it more accurate, that would be another interesting patch.

But let's not get sidetracked. We should discuss eytzinger here, feel free to open issues for the other topics so that we can discuss them separately.

**Comment by HDembinski** [comment]
The failure on Windows is caused by the new detail/prefetch.hpp code. It looks like I oversimplified the original implementation, this needs a better platform check.

**Comment by HDembinski** [comment]
> Should I `git push origin eytzinger_search` or `git fetch origin develop; git merge develop; git push origin eytzinger_search` or ...?

I just made another commit to this branch, please rebase your branch if my patch fixes the prefetch issue on Windows (or don't if you already fixed that in your branch). Then sync your local branch to your fork on GitHub. Then browse to your fork on the Github website and use the website interface to start a pull request onto boostorg/develop. This should create another PR. I should be able to make changes to your PR, so we can close this PR then.

**Comment by jhcarl0814** [comment]
@HDembinski The point 1 intends to:

1. let users use `variable_t` when possible as it maps different input types to same output type to make post processing easier;
2. `variable` should appear only when they want to:
    - template deduce the type template arguments (`V, M, O, A, ...`) in `variable<V, M, O, A, ...>` or
    - check if a type is a specialization of `variable`

(there are two implementations of `variable_t` and I commented out one of them, which one is used doesn't matter)

We can ignore this for now because it's not a big issue and it's too easy for users to add this layer of abstraction themselves.

**Comment by jhcarl0814** [comment]
The pull request is created at https://github.com/boostorg/histogram/pull/376 . (The design is very strange because a shallow type and a stateful type are occupying the same position and should be made interchangable.) I will wait for the checks and fix the syntax/semantic errors first.

**Comment by HDembinski** [comment]
> let users use variable_t when possible as it maps different input types to same output type to make post processing easier;\nvariable should appear only when they want to:\ntemplate deduce the type template arguments (V, M, O, A, ...) in variable\u003CV, M, O, A, ...> or\ncheck if a type is a specialization of variable

I still do not understand what your template alias achieves that the current implementation does not. The library was designes so you do not have to specify the template arguments. In C++14, you can use
```
variable<> my_axis;
```
To get the defaults. In C++17, you can drop the <> and let the deduction guides select the right type.

What advantages does your idea have over this scheme? What kind of additional abstraction is needed?

**Comment by jhcarl0814** [comment]
@HDembinski Here are some examples why using `variable_t` can bring convenience.

```C++
std::is_same_v<
    boost::histogram::axis::variable<double, std::string, boost::use_default>,
    boost::histogram::axis::variable<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)>
>
```
is `false`,
```C++
std::is_same_v<
    boost::histogram::axis::variable_t<double, std::string, boost::use_default>,
    boost::histogram::axis::variable_t<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)>
>
```
is `true`;

---

This causes a compile error:
```C++
boost::histogram::axis::variable<double, std::string, boost::use_default> a;
boost::histogram::axis::variable<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)> b;
a = b;
```
This does not cause a compile error:
```C++
boost::histogram::axis::variable_t<double, std::string, boost::use_default> a;
boost::histogram::axis::variable_t<double, std::string, decltype(boost::histogram::axis::option::underflow | boost::histogram::axis::option::overflow)> b;
a = b;
```

---

In templates, you can get the meta type, options type, allocator type conveniently if template users write `variable_t`, not if template users write `variable`:
```
template<typename V, typename M, typename O, typename A, typename D>
void f(boost::histogram::axis::variable<V, M, O, A, D>)
{
    std::cout << typeid(V).name() << '\n';
    std::cout << typeid(M).name() << '\n';
    std::cout << typeid(O).name() << '\n';
    std::cout << typeid(A).name() << '\n';
    std::cout << typeid(D).name() << '\n';
}

int main(int argc, char *argv[])
{
    f(boost::histogram::axis::variable<>());
    //double
    //struct boost::use_default
    //struct boost::use_default
    //class std::allocator<double>
    //struct boost::histogram::axis::sorted_array_and_binary_search

    f(boost::histogram::axis::variable_t<>());
    //double
    //class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >
    //struct boost::histogram::axis::option::bitset<3>
    //class std::allocator<double>
    //struct boost::histogram::axis::eytzinger_layout_and_eytzinger_binary_search
}
```

---

In debugger, you can not see what options `a` has but can see what options `b` has:
image
```C++
boost::histogram::axis::variable<> a;
boost::histogram::axis::variable_t<> b;
```

**Comment by HDembinski** [comment]
This PR is continued in #376

**Pull request closed without merging**
