### PR TITLE
Replace detail::span and detail::make_span with implementations in boost::core

### PR DESCRIPTION
**Pull request by HDembinski**

### CODE REVIEW

**Comment by HDembinski** [comment]
@glenfe It works like a charm now. Thanks!

**Comment by glenfe** [comment]
@HDembinski great.   Is `boost::make_span` (from `<boost/core/make_span.hpp>`) OK too?

**Comment by HDembinski** [comment]
> @HDembinski great. Is `boost::make_span` (from `<boost/core/make_span.hpp>`) OK too?

Thanks for the pointer; I missed that you also added make_span, works also fine!

**Comment by HDembinski** [comment]
> @HDembinski great. Is `boost::make_span` (from `<boost/core/make_span.hpp>`) OK too?

Thanks for the pointer; I missed that you also added make_span, works also fine!

**Comment by glenfe** [comment]
Looks good; thanks @HDembinski

**Pull request merged**
