### PR TITLE
Avoid try, catch, throw and use alloc_construct and alloc_destroy

### PR DESCRIPTION
**Pull request by glenfe**
This change:
* Uses RAII instead of try, catch, throw to achieve exception safety with or without exceptions enabled
* Uses boost::alloc_construct and boost::alloc_destroy from Boost.Core to simplify the implementation

Note that you don't need to use allocator_traits for allocate() and deallocate(). Every allocator is required to provide them.

### CODE REVIEW

**Comment by glenfe** [comment]
The failure appears to be that Appveyor is using Boost.Core from master instead of Boost.Core from develop. I'll merge Core develop to master later today.

**Comment by glenfe** [comment]
> I'll merge Core develop to master later today.

Done.

**Comment by HDembinski** [comment]
Beautiful solution, much better than using macros and makes better use of existing library code. Thank you!

**Comment by HDembinski** [comment]
> On 12. May 2019, at 18:43, Glen Fernandes <notifications@github.com> wrote:
> 
> The failure appears to be that Appveyor is using Boost.Core from master instead of Boost.Core from develop. I'll merge Core develop to master later today.

Yes, I need to fix the Appveyor build so that it correctly uses the develop and master branches, as I am doing already in Travis.

**Pull request merged**
